version: 2

project_name: foo-test

monorepo:
  tag_prefix: "foo-test-"
  dir: foo-test

env:
  - RELEASE_NOTES_COMPONENT=foo-test

includes:
  - from_file:
      path: ci/goreleaser/global.yaml

# before:
  # hooks:
    # #  Generate the release notes using our custom tool so they can be displayed in GH releases
    # - cmd: >-
        # echo "before"
        # sh scripts/before.sh

release:
  prerelease: auto
  name_template: "{{ envOrDefault \"RELEASE_NOTES_COMPONENT\" .ProjectName }}-v{{.Version}}"
  skip_upload: true
  mode: replace
  # header:
    # from_file:
      # path: "a-release-notes.md"
  footer: |
    ## Thanks

    Those were the changes on {{ .Tag }}!

